<?php

/**
 * arrangerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class arrangerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object arrangerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('arranger');
    }
}