<?php

/**
 * arrangerUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class arrangerUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object arrangerUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('arrangerUser');
    }
}