<?php

/**
 * discussionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class discussionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object discussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('discussion');
    }
}