<?php

/**
 * discussionCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class discussionCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object discussionCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('discussionCategory');
    }
}