<?php

/**
 * discussionUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class discussionUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object discussionUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('discussionUser');
    }
}