<?php

/**
 * festivalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class festivalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object festivalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('festival');
    }
}