<?php

/**
 * locationReservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class locationReservation extends BaselocationReservation
{

  public function getActivatedRequirements ()
  {
    $string = '';
    if ($this->relatedExists('requirementLightSound'))
      $string .= 'light and sound, ';

    if ($this->relatedExists('requirementPhotography'))
      $string .= 'photography, ';
    
    if ($this->relatedExists('requirementCatering'))
      $string .= 'catering, ';

    return substr($string, 0, -2);
  }
}
