<?php

/**
 * locationReservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class locationReservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locationReservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locationReservation');
    }
}
