<?php

/**
 * locationReservationRequirementBaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class locationReservationRequirementBaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locationReservationRequirementBaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locationReservationRequirementBase');
    }
}
