<?php

/**
 * locationUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class locationUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locationUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locationUser');
    }
}