<?php

/**
 * loginLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class loginLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object loginLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('loginLog');
    }
}