<?php

/**
 * requirementCateringTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class requirementCateringTable extends locationReservationRequirementBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object requirementCateringTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('requirementCatering');
    }
}