<?php

/**
 * requirementLightSoundTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class requirementLightSoundTable extends locationReservationRequirementBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object requirementLightSoundTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('requirementLightSound');
    }
}