<?php

/**
 * userTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class userTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object userTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('user');
    }
}