<?php

/**
 * user
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kvarteret_events
 * @subpackage model
 * @author     Endre Oma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class user extends Baseuser
{
    public function setPassword ($password) {
        $this->_set('password', sha1($password));
    }
}
